
const V='<span class="tag V">PUBLIC</span>',U='<span class="tag U">YOU-STATED</span>',I='<span class="tag I">INFERRED</span>',X='<span class="tag X">ILLUSTRATIVE</span>';
let GL={};let GRE=null;const esc=x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const gl=t=>!GRE?(t||''):(t||'').replace(GRE,m=>`<span class="gt" data-d="${GL[m].replace(/"/g,'&quot;')}">${m}</span>`);
let cases=[],cc=0,pg='story',selN=null,rf='all',path=[],pi=-1,timer=null;
const saveU=()=>{try{localStorage.setItem('cl_cases',JSON.stringify(cases.slice(1)))}catch(e){}};
const C=()=>cases[cc],$=id=>document.getElementById(id),fmt=n=>n.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const RC={store:'#0369a1',online:'#6d28d9',cash:'#b45309',intl:'#be123c',core:'#475569'},RN={store:'In-store',online:'Online',cash:'Cash',intl:'International'};
const CN=['CUSTOMER','CAPTURE','PA / PG / LOGISTICS','NETWORKS','SETTLEMENT','BANK & BOOKS','TREASURY & OUTFLOWS'];
const PAGES=[['story','📖 Case story'],['flow','🔀 Live money flow'],['data','📊 Dashboard'],['gloss','📚 Glossary'],['help','🧭 Where to help'],['cases','➕ Manage case studies']];
function shell(){$('sd').innerHTML=`<div class="logo"><b>◈</b><span>Case <i>Lab</i></span></div><div class="cap2">Money-flow case studies</div><label class="s">Case study</label><select onchange="cc=+this.value;rf='all';path=[];pi=-1;go(pg)">${cases.map((c,i)=>`<option value="${i}" ${i==cc?'selected':''}>${c.name}</option>`).join('')}</select><label class="s">Navigate</label>${PAGES.map(p=>`<button class="nv ${p[0]==pg?'on':''}" onclick="go('${p[0]}')">${p[1]}</button>`).join('')}<label class="s">Evidence legend</label><div style="font-size:12px;line-height:2">${V} reported in filings/press<br>${U} given in your brief<br>${I} standard industry mechanics<br>${X} placeholder value</div>`}
function go(p){stop();pg=p;shell();$('mn').innerHTML=R[p]();if(p=='flow')initFlow();if(p=='gloss')fg();if(p=='story'&&C().calc)calc();window.scrollTo(0,0)}
const R={
story:()=>{const c=C();return `<div class="hero"><span class="chip">Case study</span><span class="chip">Money-flow architecture</span><span class="chip">Live simulation</span><h1>${c.name}</h1><p>${gl(c.blurb)}</p><span class="chip">${(c.parties||[]).length} parties</span><span class="chip">${Object.keys(c.scen||{}).length} scenarios</span><span class="chip">${(c.chapters||[]).length} chapters</span></div><div class="m">${(c.kpis||[]).map(k=>`<div class="mt"><div class="l">${k[0]}</div><div class="k">${k[1]}</div><div class="n">${k[2]||''}</div></div>`).join('')}</div>
<div class="box info"><b>How to use this app.</b> Read the chapters below, then open <b>Live money flow</b> and run a transaction. Dotted underlined words are glossary terms; hover them. Add your own case study from <b>Manage case studies</b>.</div>
<h2>The journey in six chapters</h2>${(c.chapters||[]).map((h,i)=>`<details ${i==0?'open':''}><summary>${h[0]}</summary><div><div class="q"><b>Plain English</b><span>${gl(h[1])}</span></div><div class="q"><b>Why it matters</b><span>${gl(h[2])}</span></div><div class="q"><b>What can break</b><span>${gl(h[3])}</span></div></div></details>`).join('')}
${c.calc?`<h2>Try it: what actually lands in the bank?</h2><div class="box"><div class="cin"><div><span>Card/UPI sale ₹</span><input id="a1" type="number" value="3500" oninput="calc()"></div><div><span>Cash sale ₹</span><input id="a2" type="number" value="1000" oninput="calc()"></div><div><span>MDR %</span><input id="a3" type="number" step=".05" value="1.2" oninput="calc()"></div><div><span>GST on MDR %</span><input id="a4" type="number" value="18" oninput="calc()"></div></div><div id="co" style="margin-top:12px"></div><small style="color:var(--mut)">MDR and settlement values here are ${X}; real rates are contract-specific.</small></div>`:''}`},
flow:()=>`<h1>Live money flow</h1><p class="lead">Pick a scenario and press <b>Run</b>. Each step lights up the party and route with a plain-English caption. Click any box for its role, IDs, timing and break points.</p><div class="ctl"><select id="sc" onchange="setSc()"></select><button class="b on" id="rb" onclick="run()">▶ Run transaction</button><button class="b" onclick="setR('all')">All rails</button><span id="rails"></span></div><div class="cap" id="cap">▶ Choose a scenario, press Run.</div><div class="cv"><svg id="sv" viewBox="0 0 1290 560" style="min-width:1100px;width:100%"></svg></div><div class="box" id="det" style="margin-top:12px"><b>Select a party above.</b></div>`,
data:()=>{const c=C(),m=Math.max(...(c.q||[[0,1]]).map(x=>x[1])),P=c.parties||[],E=c.edges||[];
const ev=[['PUBLIC','tag V','#059669'],['YOU-STATED','tag U','#d97706'],['INFERRED','tag I','#7c3aed'],['ILLUSTRATIVE','tag X','#e11d48']].map(x=>[x[0],P.filter(p=>(p.tag||'').includes(x[1])).length,x[2]]),tot=Math.max(1,P.length);
const RCm={store:'#0369a1',online:'#6d28d9',cash:'#b45309',intl:'#be123c',core:'#475569'},rc=Object.keys(RCm).map(k=>[k,E.filter(e=>e[2]==k).length]),mx=Math.max(1,...rc.map(y=>y[1]));
const donut=a=>{let o=0;return `<svg viewBox="0 0 100 100" width="150" height="150"><circle cx="50" cy="50" r="38" fill="none" stroke="#eef2f7" stroke-width="16"/>`+a.map(x=>{const f=x[1]/100*238.76,r=`<circle cx="50" cy="50" r="38" fill="none" stroke="${x[2]}" stroke-width="16" stroke-dasharray="${f} ${238.76-f}" stroke-dashoffset="${-o}" transform="rotate(-90 50 50)"/>`;o+=f;return r}).join('')+`<text x="50" y="54" text-anchor="middle" font-size="9" font-weight="800" fill="#0f172a">Ownership</text></svg>`};
return `<h1>Dashboard</h1><p class="lead">Key numbers, ownership, and how well each part of this model is evidenced.</p><div class="m">${(c.kpis||[]).map(k=>`<div class="mt"><div class="l">${k[0]}</div><div class="k">${k[1]}</div><div class="n">${k[2]||''}</div></div>`).join('')}</div>
<div class="g2">${c.q?`<div class="box"><h3>${c.qt}</h3><div class="bar">${c.q.map(x=>`<div><i style="height:${x[1]/m*130}px"></i><b style="color:#0f172a">${x[1]}</b><br>${x[0]}</div>`).join('')}</div></div>`:''}
${c.hold?`<div class="box"><h3>${c.ht}</h3><div style="display:flex;gap:16px;align-items:center;flex-wrap:wrap">${donut(c.hold)}<div style="flex:1;min-width:150px">${c.hold.map(x=>`<div class="row"><span><span style="color:${x[2]}">●</span> ${x[0]}</span><b>${x[1]}%</b></div>`).join('')}</div></div></div>`:''}
<div class="box"><h3>Evidence coverage <small style="color:var(--mut);font-weight:400">(parties in model)</small></h3><div class="stack">${ev.filter(x=>x[1]).map(x=>`<span style="width:${x[1]/tot*100}%;background:${x[2]}">${x[1]}</span>`).join('')}</div>${ev.map(x=>`<div class="row"><span><span style="color:${x[2]}">●</span> ${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>
<div class="box"><h3>Routes by rail</h3>${rc.filter(x=>x[1]).map(x=>`<div class="row"><span style="min-width:90px">${x[0]}</span><span style="flex:1;margin:6px 10px"><i style="display:block;height:8px;border-radius:6px;background:${RCm[x[0]]};width:${x[1]/mx*100}%"></i></span><b>${x[1]}</b></div>`).join('')}</div>
${c.holders?`<div class="box"><h3>Named holders</h3>${c.holders.map(h=>`<div class="row"><span>${h[0]}</span><b>${h[1]}</b></div>`).join('')}</div>`:''}
${c.entities?`<div class="box"><h3>Entities &amp; sites</h3>${c.entities.map(h=>`<div class="row"><span>${h[0]}</span><b style="text-align:right;font-weight:500">${gl(h[1])}</b></div>`).join('')}</div>`:''}</div>${c.caveat?`<div class="box warn"><b>Data caveat.</b> ${c.caveat}</div>`:''}`},
gloss:()=>`<h1>Glossary</h1><p class="lead">Every term used in the case studies.</p><input id="gq" placeholder="Search terms…" oninput="fg()"><div id="gl" class="g2" style="margin-top:12px"></div>`,
help:()=>`<h1>Where an expert can help</h1><p class="lead">Open questions that would turn this reference model into a verified one.</p><div class="g2">${(C().gaps||[]).map(g=>`<div class="box"><h3>${g[0]}</h3>${gl(g[1])}</div>`).join('')||'<div class="box">No gaps listed for this case.</div>'}</div>`,
cases:()=>`<h1>Manage case studies</h1><p class="lead">Add a new case as JSON. Cases added here are saved in this browser only; to publish a case for everyone, add its JSON file to <code>cases/</code> and list it in <code>cases/index.json</code> in git. Fastest start: copy the Lenskart case, then edit names, parties, edges and scenarios.</p><div class="box"><b>Your cases</b>${cases.map((c,i)=>`<div class="row"><span>${c.name}</span>${i?`<button class="b" onclick="delC(${i})">Delete</button>`:'<small>built-in</small>'}</div>`).join('')}</div>
<div class="box"><b>Add a case</b><p style="margin:4px 0 8px;color:var(--mut)">Required: <code>name</code>, <code>parties</code> [{id,c,r,t,s,tag,role,data,tm,br}], <code>edges</code> [[from,to,rail]]. Optional: blurb, kpis, chapters, scen, q, hold, entities, gaps. Rails: store, online, cash, intl, core.</p><textarea id="js" rows="9" placeholder="Paste JSON here"></textarea><div class="ctl" style="margin-top:8px"><button class="b on" onclick="addC()">Add case</button><button class="b" onclick="tpl(1)">Fill with Lenskart (editable)</button><button class="b" onclick="tpl(0)">Fill with tiny example</button></div><div id="msg"></div></div>`};
function calc(){const a=+$('a1').value||0,b=+$('a2').value||0,r=+$('a3').value||0,g=+$('a4').value||0,m=a*r/100,t=m*g/100,n=a-m-t;
$('co').innerHTML=`<div class="g2"><div>${[['Aggregator net payout',n],['Cash deposit via CIT',b],['Bank credit total',n+b]].map(x=>`<div class="row"><span>${x[0]}</span><b>₹${fmt(x[1])}</b></div>`).join('')}</div><div>${[['Dr Bank',n+b],['Dr MDR expense',m],['Dr GST input credit',t],['Cr Retail sales',a+b]].map(x=>`<div class="row"><span>${x[0]}</span><b>₹${fmt(x[1])}</b></div>`).join('')}<div class="row"><span>Debits = credits?</span><b style="color:var(--g)">${Math.abs(n+b+m+t-(a+b))<.005?'✓ balanced':'✗'}</b></div></div></div>`}
function fg(){const q=($('gq')?$('gq').value:'').toLowerCase();$('gl').innerHTML=Object.keys(GL).sort((a,b)=>a.localeCompare(b)).filter(k=>(k+GL[k]).toLowerCase().includes(q)).map(k=>`<div class="box" style="margin:0"><b style="color:var(--a)">${k}</b><div style="color:var(--mut);font-size:13px;margin-top:2px">${GL[k]}</div></div>`).join('')}
const NT={name:'Mini case · Coffee chain',blurb:'Example skeleton.',parties:[{id:'a',c:0,r:1,t:'Customer',s:'Pays',tag:'',role:'Buys coffee.',data:'Receipt',tm:'Instant',br:'Decline'},{id:'b',c:1,r:1,t:'POS',s:'Terminal',tag:'',role:'Takes payment.',data:'TID',tm:'Seconds',br:'Offline'},{id:'c',c:2,r:1,t:'Bank',s:'Settles',tag:'',role:'Receives funds.',data:'UTR',tm:'T+1',br:'Mismatch'}],edges:[['a','b','store'],['b','c','store']],scen:{'Card sale':['store',['a','b','c'],['Customer pays','POS authorises','Bank settles']]}};
function tpl(k){$('js').value=JSON.stringify(k?C0:NT,null,1)}
function addC(){try{const j=JSON.parse($('js').value);if(!j.name||!Array.isArray(j.parties)||!Array.isArray(j.edges))throw'Need name, parties[], edges[]';j.parties.forEach(p=>{p.c=+p.c;p.r=+p.r;p.tag=p.tag||''});if(!j.scen)j.scen={'Default':['store',j.parties.map(p=>p.id),j.parties.map(p=>p.t)]};if(j.name==cases[0].name)j.name+=' (copy)';cases.push(j);saveU();cc=cases.length-1;go('story')}catch(e){$('msg').innerHTML='<div class="box warn">Could not add: '+e+'</div>'}}
function delC(i){cases.splice(i,1);saveU();cc=0;go('cases')}
const P_=()=>C().parties,E_=()=>C().edges;
const pos_=n=>({x:10+180*n.c,y:34+n.r*105});
function geo(a,b){const A=pos_(P_().find(n=>n.id==a)),B=pos_(P_().find(n=>n.id==b)),W=150,H=66;if(A.x==B.x){const d=B.y>A.y;return `M${A.x+W/2},${A.y+(d?H:0)} L${B.x+W/2},${B.y+(d?0:H)}`}const x1=A.x+W,y1=A.y+H/2,x2=B.x,y2=B.y+H/2,m=(x1+x2)/2;return `M${x1},${y1} C${m},${y1} ${m},${y2} ${x2},${y2}`}
function drawFlow(){const act=new Set(path.slice(0,pi+1)),aE=new Set();for(let i=1;i<=pi;i++)aE.add(path[i-1]+'>'+path[i]);const ok=r=>rf=='all'||rf==r||r=='core';
let h='<defs><pattern id="gd" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="#e5e9f2"/></pattern></defs><rect width="1290" height="560" fill="url(#gd)"/>';
h+=CN.map((c,i)=>`<rect x="${180*i+4}" y="4" width="162" height="26" rx="13" fill="${i%2?'#eef2ff':'#f1f5f9'}"/><text x="${85+180*i}" y="21" text-anchor="middle" font-size="9.5" font-weight="700" fill="#475569" letter-spacing=".07em">${c}</text>`).join('');
const L=E_().map(e=>({e,on:aE.has(e[0]+'>'+e[1]),d:geo(e[0],e[1]),col:RC[e[2]]||'#475569',v:ok(e[2])}));
h+=L.map(l=>`<path class="e ${l.v?'':'dim'} ${l.on?'act':''}" d="${l.d}" stroke="${l.on?'#059669':l.col}"/>`).join('');
h+=L.filter(l=>l.v).map((l,i)=>`<circle r="${l.on?5:3.2}" fill="${l.on?'#059669':l.col}"><animateMotion dur="${l.on?1.6:3.4+(i%4)*.4}s" repeatCount="indefinite" path="${l.d}"/></circle>`).join('');
h+=P_().map(n=>{const p=pos_(n),rs=E_().filter(e=>e[0]==n.id||e[1]==n.id).map(e=>e[2]),vis=rf=='all'||rs.includes(rf)||n.c==0,pr=rs.find(r=>r!='core')||'core',col=RC[pr]||'#475569';
return `<g class="nd ${vis?'':'dim'} ${selN==n.id?'sel':''} ${act.has(n.id)?'act':''}" onclick="pick('${n.id}')"><rect class="bx" x="${p.x}" y="${p.y}" width="150" height="66" rx="11"/><rect x="${p.x}" y="${p.y+10}" width="4" height="46" rx="2" fill="${col}"/><circle cx="${p.x+20}" cy="${p.y+22}" r="3.5" fill="${col}"/><text x="${p.x+30}" y="${p.y+26}" font-size="12.5" font-weight="700" fill="#0f172a">${n.t}</text><text x="${p.x+16}" y="${p.y+47}" font-size="10.5" fill="#64748b">${n.s}</text></g>`}).join('');
$('sv').innerHTML=h;$('rails').innerHTML=Object.keys(RN).map(k=>`<button class="b ${rf==k?'on':''}" style="${rf==k?'':'border-left:4px solid '+RC[k]}" onclick="setR('${k}')">${RN[k]}</button>`).join(' ')}
const setR=r=>{rf=r;drawFlow()};
function initFlow(){const s=$('sc'),k=Object.keys(C().scen||{});s.innerHTML=k.map(x=>`<option>${x}</option>`).join('');path=[];pi=-1;rf='all';drawFlow()}
function setSc(){stop();const S=C().scen[$('sc').value];path=S[1];pi=-1;rf=S[0];$('cap').textContent='Press Run to play: '+$('sc').value;drawFlow()}
function stop(){clearInterval(timer);timer=null;const b=$('rb');if(b)b.textContent='▶ Run transaction'}
function run(){if(timer){stop();return}const S=C().scen[$('sc').value];path=S[1];pi=-1;rf=S[0];$('rb').textContent='⏸ Pause';const st=()=>{pi++;if(pi>=path.length){stop();return}$('cap').innerHTML=`<b>Step ${pi+1} of ${path.length}</b> · ${gl(S[2][pi]||'')}`;drawFlow()};st();timer=setInterval(st,2000)}
function pick(id){selN=id;const n=P_().find(x=>x.id==id);drawFlow();const f=k=>E_().filter(e=>e[k]==id).map(e=>P_().find(p=>p.id==e[1-k]).t).join(', ')||'—';$('det').innerHTML=`<h3>${n.t} ${n.tag}</h3><div class="dl"><div><b>Role</b><span>${gl(n.role)}</span></div><div><b>Data / IDs</b><span>${gl(n.data)}</span></div><div><b>Timing</b><span>${gl(n.tm)}</span></div><div><b>Break points</b><span>${gl(n.br)}</span></div><div><b>Receives from</b><span>${f(1)}</span></div><div><b>Sends to</b><span>${f(0)}</span></div></div>`}
async function boot(){try{GL=await (await fetch('glossary.json')).json();GRE=new RegExp('(?<![\\w.])('+Object.keys(GL).sort((a,b)=>b.length-a.length).map(esc).join('|')+')(?![\\w])','g');
const ix=await (await fetch('cases/index.json')).json();cases=await Promise.all(ix.map(f=>fetch('cases/'+f).then(r=>r.json())));
try{JSON.parse(localStorage.getItem('cl_cases')||'[]').forEach(c=>cases.push(c))}catch(e){}go('story')}catch(e){document.getElementById('mn').innerHTML='<div class="box warn"><b>Could not load case files.</b> Serve this folder over http (e.g. <code>python3 -m http.server</code>) instead of opening index.html directly.<br>'+e+'</div>'}}
boot();
